import math
a=int(input("Enter the first number :"))
b=int(input("Enter the second number :"))
print("Addition of the numbers is :",a+b)
print("Subtraction of the numbers is :",a-b)
print("Multiplication of the numbers is :",a*b)
print("Divison of the numbers is :",a/b)
print("The maxmimum numbers is :",max(a,b))
print("The minimum numbers is :",min(a,b))
print("Square of a is :",a*a)
print("Square of b is :",b*b)
print("Cube of a is :",a*a*a)
print("Cube of b is :",b*b*b)
print("Square root of a is :",math.sqrt(a))
print("Square root of b is :",math.sqrt(b))
